extends: ../.eslintrc.yml

rules:
  class-methods-use-this:
    - error
    - exceptMethods:
      - media
      - matches
      - addListener
      - removeListener
      - addEventListener
      - removeEventListener
